BEGIN {
    FS="[, ;	]";
    printf "//\n";
    printf "//\n";
    printf "// CROM.DAT\n";
    printf "// This code is extracted from the KS10 microcode listing by an\n";
    printf "// AWK script.   DO NOT EDIT THIS FILE!\n";
    printf "//\n";
    printf "//\n";
    printf "\n";
}

/U [0-7][0-7][0-7][0-7], / {
    #print $4 " " $5 " " $6 " " $7 " " $8 " " $9 " " $10 " " $11 " " $12 "// " $2
    i         = strtonum("0"  $2);
    MAP2[i]   = strtonum("0"  $2);
    MAP[ 4,i] = strtonum("0"  $4);
    MAP[ 5,i] = strtonum("0"  $5);
    MAP[ 6,i] = strtonum("0"  $6);
    MAP[ 7,i] = strtonum("0"  $7);
    MAP[ 8,i] = strtonum("0"  $8);
    MAP[ 9,i] = strtonum("0"  $9);
    MAP[10,i] = strtonum("0" $10);
    MAP[11,i] = strtonum("0" $11);
    MAP[12,i] = strtonum("0" $12);
}

END {
    for (i = 0; i < 04000; i++) {
	if (MAP2[i] == i) {
	    printf "%03x%03x%03x%03x%03x%03x%03x%03x%03x	// CROM[%4d] = 108'o%04o_%04o_%04o_%04o_%04o_%04o_%04o_%04o_%04o;\n",
		MAP[ 4,i], MAP[ 5,i], MAP[ 6,i], MAP[ 7,i], MAP[ 8,i], MAP[ 9,i], MAP[10,i], MAP[11,i], MAP[12,i], i,
		MAP[ 4,i], MAP[ 5,i], MAP[ 6,i], MAP[ 7,i], MAP[ 8,i], MAP[ 9,i], MAP[10,i], MAP[11,i],	MAP[12,i]
	} else {
	    printf "%03x%03x%03x%03x%03x%03x%03x%03x%03x	// CROM[%4d] = 108'o%04o_%04o_%04o_%04o_%04o_%04o_%04o_%04o_%04o;	// Unused\n",
		0, 0, 0, 0, 0, 0, 0, 0, 0, i,
		0, 0, 0, 0, 0, 0, 0, 0, 0
	}
    }
}
