# TCL File Generated by Component Editor 18.1
# Wed Dec 28 14:30:15 MST 2022
# DO NOT MODIFY


# 
# ks10 "DEC KS10 Processor" v1.0
# Rob Doyle 2022.12.28.14:30:15
# DEC KS10 Processor
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ks10
# 
set_module_property DESCRIPTION "DEC KS10 Processor"
set_module_property NAME ks10
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Rob Doyle"
set_module_property DISPLAY_NAME "DEC KS10 Processor"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL KS10
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false


# 
# parameters
# 


# 
# display items
# 


# 
# connection point altera_axi4lite_slave
# 
add_interface altera_axi4lite_slave axi4lite end
set_interface_property altera_axi4lite_slave associatedClock cpuCLK
set_interface_property altera_axi4lite_slave associatedReset rst
set_interface_property altera_axi4lite_slave readAcceptanceCapability 1
set_interface_property altera_axi4lite_slave writeAcceptanceCapability 1
set_interface_property altera_axi4lite_slave combinedAcceptanceCapability 1
set_interface_property altera_axi4lite_slave readDataReorderingDepth 1
set_interface_property altera_axi4lite_slave bridgesToMaster ""
set_interface_property altera_axi4lite_slave ENABLED true
set_interface_property altera_axi4lite_slave EXPORT_OF ""
set_interface_property altera_axi4lite_slave PORT_NAME_MAP ""
set_interface_property altera_axi4lite_slave CMSIS_SVD_VARIABLES ""
set_interface_property altera_axi4lite_slave SVD_ADDRESS_GROUP ""

add_interface_port altera_axi4lite_slave axiARADDR araddr Input 8
add_interface_port altera_axi4lite_slave axiARREADY arready Output 1
add_interface_port altera_axi4lite_slave axiAWADDR awaddr Input 8
add_interface_port altera_axi4lite_slave axiARVALID arvalid Input 1
add_interface_port altera_axi4lite_slave axiAWREADY awready Output 1
add_interface_port altera_axi4lite_slave axiAWVALID awvalid Input 1
add_interface_port altera_axi4lite_slave axiBVALID bvalid Output 1
add_interface_port altera_axi4lite_slave axiBREADY bready Input 1
add_interface_port altera_axi4lite_slave axiBRESP bresp Output 2
add_interface_port altera_axi4lite_slave axiRDATA rdata Output 32
add_interface_port altera_axi4lite_slave axiRREADY rready Input 1
add_interface_port altera_axi4lite_slave axiRRESP rresp Output 2
add_interface_port altera_axi4lite_slave axiRVALID rvalid Output 1
add_interface_port altera_axi4lite_slave axiWDATA wdata Input 32
add_interface_port altera_axi4lite_slave axiWREADY wready Output 1
add_interface_port altera_axi4lite_slave axiWSTRB wstrb Input 4
add_interface_port altera_axi4lite_slave axiWVALID wvalid Input 1
add_interface_port altera_axi4lite_slave axiARPROT arprot Input 3
add_interface_port altera_axi4lite_slave axiAWPROT awprot Input 3


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 50000000
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point SSRAM
# 
add_interface SSRAM conduit end
set_interface_property SSRAM associatedClock clk
set_interface_property SSRAM associatedReset ""
set_interface_property SSRAM ENABLED true
set_interface_property SSRAM EXPORT_OF ""
set_interface_property SSRAM PORT_NAME_MAP ""
set_interface_property SSRAM CMSIS_SVD_VARIABLES ""
set_interface_property SSRAM SVD_ADDRESS_GROUP ""

add_interface_port SSRAM SSRAM_CLK clk Output 1
add_interface_port SSRAM SSRAM_WE_N we_n Output 1
add_interface_port SSRAM SSRAM_A a Output 22
add_interface_port SSRAM SSRAM_D d Bidir 36
add_interface_port SSRAM SSRAM_ADV adv Output 1


# 
# connection point DZ11
# 
add_interface DZ11 conduit end
set_interface_property DZ11 associatedClock cpuCLK
set_interface_property DZ11 associatedReset ""
set_interface_property DZ11 ENABLED true
set_interface_property DZ11 EXPORT_OF ""
set_interface_property DZ11 PORT_NAME_MAP ""
set_interface_property DZ11 CMSIS_SVD_VARIABLES ""
set_interface_property DZ11 SVD_ADDRESS_GROUP ""

add_interface_port DZ11 DZ_DTR dtr Output 8
add_interface_port DZ11 DZ_RXD rxd Input 8
add_interface_port DZ11 DZ_TXD txd Output 8


# 
# connection point LP26
# 
add_interface LP26 conduit end
set_interface_property LP26 associatedClock cpuCLK
set_interface_property LP26 associatedReset ""
set_interface_property LP26 ENABLED true
set_interface_property LP26 EXPORT_OF ""
set_interface_property LP26 PORT_NAME_MAP ""
set_interface_property LP26 CMSIS_SVD_VARIABLES ""
set_interface_property LP26 SVD_ADDRESS_GROUP ""

add_interface_port LP26 LP_RXD rxd Input 1
add_interface_port LP26 LP_TXD txd Output 1


# 
# connection point RPxx
# 
add_interface RPxx conduit end
set_interface_property RPxx associatedClock cpuCLK
set_interface_property RPxx associatedReset ""
set_interface_property RPxx ENABLED true
set_interface_property RPxx EXPORT_OF ""
set_interface_property RPxx PORT_NAME_MAP ""
set_interface_property RPxx CMSIS_SVD_VARIABLES ""
set_interface_property RPxx SVD_ADDRESS_GROUP ""

add_interface_port RPxx RP_LEDS leds Output 8


# 
# connection point SD
# 
add_interface SD conduit end
set_interface_property SD associatedClock cpuCLK
set_interface_property SD associatedReset ""
set_interface_property SD ENABLED true
set_interface_property SD EXPORT_OF ""
set_interface_property SD PORT_NAME_MAP ""
set_interface_property SD CMSIS_SVD_VARIABLES ""
set_interface_property SD SVD_ADDRESS_GROUP ""

add_interface_port SD SD_CD cd Input 8
add_interface_port SD SD_WP wp Input 8
add_interface_port SD SD_SS_N ss_n Output 1
add_interface_port SD SD_MISO miso Input 1
add_interface_port SD SD_MOSI mosi Output 1
add_interface_port SD SD_SCLK sclk Output 1


# 
# connection point FP
# 
add_interface FP conduit end
set_interface_property FP associatedClock cpuCLK
set_interface_property FP associatedReset ""
set_interface_property FP ENABLED true
set_interface_property FP EXPORT_OF ""
set_interface_property FP PORT_NAME_MAP ""
set_interface_property FP CMSIS_SVD_VARIABLES ""
set_interface_property FP SVD_ADDRESS_GROUP ""

add_interface_port FP SW_RESET_N sw_reset_n Input 1
add_interface_port FP SW_BOOT_N sw_boot_n Input 1
add_interface_port FP SW_HALT_N sw_halt_n Input 1
add_interface_port FP LED_PWR_N led_pwr_n Output 1
add_interface_port FP LED_RESET_N led_reset_n Output 1
add_interface_port FP LED_BOOT_N led_boot_n Input 1
add_interface_port FP LED_HALT_N led_halt_n Output 1


# 
# connection point cpuCLK
# 
add_interface cpuCLK clock start
set_interface_property cpuCLK associatedDirectClock cpuCLK
set_interface_property cpuCLK clockRate 12500000
set_interface_property cpuCLK clockRateKnown false
set_interface_property cpuCLK ENABLED true
set_interface_property cpuCLK EXPORT_OF ""
set_interface_property cpuCLK PORT_NAME_MAP ""
set_interface_property cpuCLK CMSIS_SVD_VARIABLES ""
set_interface_property cpuCLK SVD_ADDRESS_GROUP ""

add_interface_port cpuCLK cpuCLK clk Output 1


# 
# connection point ESD
# 
add_interface ESD conduit end
set_interface_property ESD associatedClock cpuCLK
set_interface_property ESD associatedReset ""
set_interface_property ESD ENABLED true
set_interface_property ESD EXPORT_OF ""
set_interface_property ESD PORT_NAME_MAP ""
set_interface_property ESD CMSIS_SVD_VARIABLES ""
set_interface_property ESD SVD_ADDRESS_GROUP ""

add_interface_port ESD ESD_SCLK sclk Output 1
add_interface_port ESD ESD_DO do Output 1
add_interface_port ESD ESD_DI di Input 1
add_interface_port ESD ESD_CS_N cs_n Output 1
add_interface_port ESD ESD_RST_N rst_n Output 1
add_interface_port ESD ESD_RD_N rd_n Output 1
add_interface_port ESD ESD_WR_N wr_n Output 1
add_interface_port ESD ESD_ADDR addr Output 5
add_interface_port ESD ESD_DIO dio Bidir 1


# 
# connection point cpuRST
# 
add_interface cpuRST reset start
set_interface_property cpuRST associatedClock cpuCLK
set_interface_property cpuRST associatedDirectReset rst
set_interface_property cpuRST associatedResetSinks ""
set_interface_property cpuRST synchronousEdges BOTH
set_interface_property cpuRST ENABLED true
set_interface_property cpuRST EXPORT_OF ""
set_interface_property cpuRST PORT_NAME_MAP ""
set_interface_property cpuRST CMSIS_SVD_VARIABLES ""
set_interface_property cpuRST SVD_ADDRESS_GROUP ""

add_interface_port cpuRST cpuRST reset Output 1


# 
# connection point rst
# 
add_interface rst reset end
set_interface_property rst associatedClock clk
set_interface_property rst synchronousEdges DEASSERT
set_interface_property rst ENABLED true
set_interface_property rst EXPORT_OF ""
set_interface_property rst PORT_NAME_MAP ""
set_interface_property rst CMSIS_SVD_VARIABLES ""
set_interface_property rst SVD_ADDRESS_GROUP ""

add_interface_port rst rst reset Input 1

