BEGIN {
    printf "//\n";
    printf "//\n";
    printf "// RAMFILE.DAT\n";
    printf "// This code is automatically generated by an AWK script.\n";
    printf "// DO NOT EDIT THIS FILE!\n";
    printf "//\n";
    printf "//\n";
    printf "\n";

    for (i = 0; i < 1024; i++) {
        if (i == 15)
            printf("ffdfc30c3           // RAMFILE[%4d] = 777577_030303 (Initialize stack pointer)\n", i);
        else
            printf("000000000           // RAMFILE[%4d] = 000000_000000\n", i);
    }
}
