#
# Copyright 2022 Rob Doyle
# SPDX-License-Identifier: GPL-2.0
#

all:
	make -C KS10\ Diagnostics
	make -C KS10\ Microcode
	make -C TOPS10
	make -C RED\ PACK\ 405A2

clean :
	make -C KS10\ Diagnostics clean
	make -C KS10\ Microcode clean
	make -C TOPS10 clean
	make -C RED\ PACK\ 405A2 clean
