!
! BUILD KS10 MICROCODE FROM SCRATCH
!
!
! FIRST BUILD ASSEMBLER
!
@GET SYS:MACRO.EXE
@VD SYS:MACRO.EXE.0,
@CHECK SEQ
@
@I VER
@START
*MICRO.REL=MICRO.MAC
@VD MICRO.REL,
@CHECK SEQ
@
@GET SYS:LINK
@VD SYS:LINK.EXE.0,SYS:SCAN.REL.0,SYS:HELPER.REL,
@CHECK SEQ
@
@I VER
@START
*MICRO.REL/G
@SAVE MICRO.EXE
@DELETE MICRO.REL !NO LONGER NEEDED
@VD MICRO.EXE.0,
@CHECK SEQ
@
!
! NOW BUILD THE MICROCODE
!
@VD *.MIC.0,KS10.CMD.0,
@CHECK SEQ
@
@RUN MICRO.EXE
*@KS10
@VD KS10.ULD.0,KS10.MCR.0,
@CHECK SEQ
@
!
! NOW BUILD THE CHECK PROGRAM
!
@VD CHECK.MAC.0,
@CHECK SEQ
@
@RUN SYS:MACRO !SAME VERSION AND CHECKSUM AS ABOVE
*CHECK.REL=CHECK.MAC,KS10.MCR
@VD CHECK.REL,
@CHECK SEQ
@
@RUN SYS:LINK !SAVE VERSION AND CHECKSUM AS ABOVE
*CHECK/G
@SAVE CHECK.EXE
@DELETE CHECK.REL !NO LONGER NEEDED
@VD CHECK.EXE.0,
@CHECK SEQ
@
!
! NOW RUN THE CHECK PROGRAM OVER THE LISTING
!
@RUN CHECK
*KS10.MCR.0
*Y
@IF (ERROR) *Y
*N
@VD KS10.MCR.0,
@CHECK SEQ
@
@PLEASE KS10 MICROCODE BUILD COMPLETED CORRECTLY
@GOTO DONE
%CERR::
%ERR::
@PLEASE ERROR BUILDING KS10 MICROCODE
@GOTO DONE
%TERR::
@PLEASE TIME LIMIT EXCEEDED BUILDING KS10 MICROCODE
DONE::
!
! WE ARE ALL DONE BATCH WILL LOG US OUT
!
