#
# Copyright 2022 Rob Doyle
# SPDX-License-Identifier: GPL-2.0
#

all : 
	make -C asm10
	make -C tapeutils
	make -C sav2verilog

clean :
	make -C asm10 clean
	make -C tapeutils clean
	make -C sav2verilog clean
